;__________________________________________________________________________________________/ common.asm    
;   Author: Joris Rietveld  <jorisrietveld@gmail.com>
;   Created: 07-06-2018 18:29
;   
;   Description:
;
%ifndef __COMM_INC_INCLUDED__
%define __COMM_INC_INCLUDED__

%include 'intel16/ascii.inc'
%include 'intel16/bios.inc'
%include 'intel16/types.inc'
%include 'intel16/jorix_debug.inc'

%endif ; __COMM_INC_INCLUDED__
